#!/usr/bin/env python

##
##  See COPYING file distributed along with the ncanda-data-integration package
##  for the copyright and license terms
##

import argparse
import re
import pandas

# Setup command line parser
parser = argparse.ArgumentParser( description="Read a LimeSurvey CSV file and produce a lookup table of original, REDCap, and R field names" )
parser.add_argument( "prefix", help="Form prefix for REDCap field names" )
parser.add_argument( "infile", help="Input .csv LimeSurvey file." )
args = parser.parse_args()

data = pandas.read_csv( args.infile )

for label in data.columns.tolist():
    redcap = "%s_%s" % (args.prefix, re.sub( '_$', '', re.sub( '[_\W]+', '_', re.sub( 'subjid', 'subject_id', label.lower() ) ) ) )

    match_brackets = re.match( '.*\[(.*)\].*', label.lower() )
    if match_brackets:
        ucsd = match_brackets.group( 1 )
    else:
        ucsd = label.lower()

    ucsd_redcap = "%s_%s" % (args.prefix, re.sub( '_$', '', re.sub( '[_\W]+', '_', re.sub( 'subjid', 'subject_id', ucsd ) ) ) )

        
    print '"%s",%s,%s,%s' % (label,redcap,ucsd_redcap,ucsd)
