#!/bin/bash

##
##  See COPYING file distributed along with the ncanda-data-integration package
##  for the copyright and license terms
##

bindir=`dirname $0`
tmpdir=`mktemp -d`


# Read specific flags
original_args="$*"
selected_args=""
# Sort out argument options starting with -p, -v, -h, -t and ignore everything else 
# : means that t has a required argument afterwards 
options=$(getopt -o pt:vh -- "$@" 2> /dev/null) ;
eval set -- "$options"
helpFlag=false
while true; do
     case ${1} in
         -p|-v) selected_args+="${1} " ;;
	 -h)  selected_args+="${1} "; helpFlag=true ;;
         -t)  shift; selected_args+="-t ${1} " ;;
         --)  break;; 
     esac
     shift 
done
# reset input to original 
eval set -- "$original_args"

#
# First, retrieve XLS file from Penn via Selenium
#
${bindir}/get_results_selenium $* ${tmpdir} 

if ${helpFlag}; then
    exit 0 
fi  

#
# Second, upload CSV file to REDCap
#
for csv in `cd ${tmpdir}; ls | fgrep .csv`; do
    if ! ${bindir}/csv2redcap ${selected_args} --import-all ${tmpdir}/${csv}; then
	rm -rf  $tmpdir
	exit 1
    fi
done

#
# Third, update summary records
#
${bindir}/update_summary_forms ${selected_args} --max-days-after-visit 120

#
# Finally, clean up
#
rm -rf ${tmpdir}
