#!/bin/bash

##
##  See COPYING file distributed along with the ncanda-data-integration package
##  for the copyright and license terms
##

bindir=`dirname $0`
tmpdir=`mktemp -d`

#
# First, retrieve XLS file from Penn via Selenium
#
CMD="${bindir}/get_results_api.py $* ${tmpdir}"
$CMD

# exit if run with help flag -h
if [ `echo "$*" | grep -c "\-h "` -eq 1 ]; then
    echo "INFO: run with help flag so not running rest of script" 
    exit 0 
fi  

# upload to redcap and update summary scores 
${bindir}/complete_csv2redcap_import $tmpdir $*

#
# Finally, clean up
#
rm -rf ${tmpdir}
