#!/bin/bash

##
##  Copyright 2013 SRI International
##
##  http://nitrc.org/projects/ncanda-datacore/
##
##  This file is part of the N-CANDA Data Component Software Suite, developed
##  and distributed by the Data Integration Component of the National
##  Consortium on Alcohol and NeuroDevelopment in Adolescence, supported by
##  the U.S. National Institute on Alcohol Abuse and Alcoholism (NIAAA) under
##  Grant No. 1U01 AA021697
##
##  The N-CANDA Data Component Software Suite is free software: you can
##  redistribute it and/or modify it under the terms of the GNU General Public
##  License as published by the Free Software Foundation, either version 3 of
##  the License, or (at your option) any later version.
##
##  The N-CANDA Data Component Software Suite is distributed in the hope that it
##  will be useful, but WITHOUT ANY WARRANTY; without even the implied
##  warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##  GNU General Public License for more details.
##
##  You should have received a copy of the GNU General Public License along
##  with the N-CANDA Data Component Software Suite.  If not, see
##  <http://www.gnu.org/licenses/>.
##
##  $Revision: 80 $
##
##  $LastChangedDate: 2013-02-25 13:45:11 -0800 (Mon, 25 Feb 2013) $
##
##  $LastChangedBy: torstenrohlfing $
##


bindir=`dirname $0`
tmpdir=`mktemp -d`

#
# First, start virtual X server and retrieve XLS file from Penn via Selenium
#
Xvfb +extension RANDR :666 >& /dev/null &
xpid=$!
export DISPLAY=:666
${bindir}/get_results_selenium $* ${tmpdir}
unset DISPLAY
#kill $xpid

#
# Second, upload CSV file to REDCap
#
for csv in `cd ${tmpdir}; ls | fgrep .csv`; do
    if ! ${bindir}/csv2redcap --import-all ${tmpdir}/${csv}; then
	echo $tmpdir
	exit 1
    fi
done

#
# Third, update summary records
#
${bindir}/update_summary_forms --max-days-after-visit 120

#
# Finally, clean up
#
rm -rf ${tmpdir}
