#!/bin/bash

##
##  Copyright 2016 SRI International
##  See COPYING file distributed along with the package for the copyright and license terms.
##

# Set the SIBIS environment variable to the data integration repo
export SIBIS=${HOME}/ncanda-data-integration

# When generating a release do not update pipeline
# exit 0
[ -r $HOME/.bashrc ] && . $HOME/.bashrc

# Import some useful functions
. $(dirname $0)/crontools.sh

# Import data from XNAT into REDCap and feed image analysis pipeline
catch_output_email ncanda-admin@sri.com "NCANDA Pipeline Feeder Messages (import_mr_sessions)" ${SIBIS}/scripts/redcap/import_mr_sessions --max-days-after-visit 120 --pipeline-root-dir /fs/ncanda-share/pipeline/cases --run-pipeline-script /fs/ncanda-share/pipeline/scripts/bin/ncanda_all_pipelines

# Export NP/clinical/dempgraphics data into image analysis pipeline directories
#   This needs to come AFTER "import_mr_sessions", because otherwise we cannot get ages-at-MRI from REDCap for the export.
catch_output_email ncanda-admin@sri.com "NCANDA Pipeline REDCap Exporter Messages (export_measures)" ${SIBIS}/scripts/redcap/export_measures --datadict-dir /fs/ncanda-share/pipeline/datadict --locked_form_report /fs/ncanda-share/pipeline/cases

# Update CSV summary files for the working pipeline
catch_output_email ncanda-admin@sri.com "NCANDA Pipeline Summaries (update_csv_summaries)" /fs/ncanda-share/pipeline/scripts/utils/update_csv_summaries /fs/ncanda-share/pipeline/cases/ /fs/ncanda-share/pipeline/summaries/

# Remove pyxnat cache directory to conserve space
catch_output_email ncanda-admin@sri.com "NCANDA Drop pyXNAT Cache Directory" rm -rf /tmp/RestAPI@localhost_8080.xnat /tmp/cache
