#!/bin/bash

##
##  Copyright 2013-2014 SRI International
##
##  http://nitrc.org/projects/ncanda-datacore/
##
##  This file is part of the N-CANDA Data Component Software Suite, developed
##  and distributed by the Data Integration Component of the National
##  Consortium on Alcohol and NeuroDevelopment in Adolescence, supported by
##  the U.S. National Institute on Alcohol Abuse and Alcoholism (NIAAA) under
##  Grant No. 1U01 AA021697
##
##  The N-CANDA Data Component Software Suite is free software: you can
##  redistribute it and/or modify it under the terms of the GNU General Public
##  License as published by the Free Software Foundation, either version 3 of
##  the License, or (at your option) any later version.
##
##  The N-CANDA Data Component Software Suite is distributed in the hope that it
##  will be useful, but WITHOUT ANY WARRANTY; without even the implied
##  warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##  GNU General Public License for more details.
##
##  You should have received a copy of the GNU General Public License along
##  with the N-CANDA Data Component Software Suite.  If not, see
##  <http://www.gnu.org/licenses/>.
##
##  $Revision: 120 $
##
##  $LastChangedDate: 2013-03-12 21:16:42 -0700 (Tue, 12 Mar 2013) $
##
##  $LastChangedBy: torsten_at_home $
##

# When generating a release do not update pipeline
# exit 0
[ -r $HOME/.bashrc ] && . $HOME/.bashrc

# Import some useful functions
. $(dirname $0)/crontools.sh

# Import data from XNAT into REDCap and feed image analysis pipeline
catch_output_email kilian.pohl@sri.com,nolan.nichols@gmail.com "NCANDA Pipeline Feeder Messages (import_mr_sessions)" ${HOME}/scripts/redcap/import_mr_sessions --max-days-after-visit 120 --pipeline-root-dir /fs/ncanda-share/pipeline/cases --run-pipeline-script /fs/ncanda-share/pipeline/scripts/bin/ncanda_all_pipelines

# Export NP/clinical/dempgraphics data into image analysis pipeline directories
#   This needs to come AFTER "import_mr_sessions", because otherwise we cannot get ages-at-MRI from REDCap for the export.
catch_output_email weiwei.chu@sri.com,nolan.nichols@gmail.com "NCANDA Pipeline REDCap Exporter Messages (export_measures)" ${HOME}/scripts/redcap/export_measures --datadict-dir /fs/ncanda-share/pipeline/datadict --locked_form_report /fs/ncanda-share/pipeline/cases 

# Update CSV summary files for the working pipeline
catch_output_email weiwei.chu@sri.com,nolan.nichols@gmail.com "NCANDA Pipeline Summaries (update_csv_summaries)" /fs/ncanda-share/pipeline/scripts/utils/update_csv_summaries /fs/ncanda-share/pipeline/cases/ /fs/ncanda-share/pipeline/summaries/

# Remove pyxnat cache directory to conserve space
catch_output_email kilian.pohl@sri.com,nolan.nichols@gmail.com "NCANDA Drop pyXNAT Cache Directory" rm -rf /tmp/RestAPI@localhost_8080.xnat /tmp/cache
