#!/bin/bash -l

##
##  See COPYING file distributed along with the ncanda-data-integration package
##  for the copyright and license terms
##
qa_args="$*"
# Set the SIBIS environment variable to the data integration repo
export SIBIS=`realpath $(dirname $0)/../../`

XNAT_FLAG=1
IMPORT_FLAG=1

[ -r $HOME/.bashrc ] && . $HOME/.bashrc

# Import some useful functions
. $(dirname $0)/crontools.sh

hour=$(date +%H)

# if no Log Dir is defined after -t option simply add default
LOG_DIR=${SIBIS_ANALYSIS_DIR}log/front-hourly
if  [ "`echo "$qa_args" | sed -e 's/\ *$//g' | rev | cut -d' ' -f1 | rev`" == "-t" ]; then
    qa_args="$qa_args $LOG_DIR"
fi

# Run QA on fBIRN and ADNI phantom scans
if [ ${XNAT_FLAG} == 1 ]; then
   catch_output_email "${SCRIPT_LABEL}:XNAT: QA Phantoms (phantom_qa)" ${SIBIS}/scripts/xnat/phantom_qa  ${qa_args}
fi

# Import data from the sites' data capture laptops into REDCap and reconcile imported with longitudinal data
if [ ${IMPORT_FLAG} == 1 ]; then
   lastWeek=""
   # do that so that if the script was interrupted the svn update is performed again - otherwise would loose data 
   if [ ${hour} -eq 20 ]; then
	lastWeek="--last-week"
   fi	
   catch_output_email "${SCRIPT_LABEL}:Import Laptop: Data Stage 1 (harvester)" ${SIBIS}/scripts/import/laptops/harvester --only-converter-post-to-github ${qa_args} ${lastWeek}

   catch_output_email "${SCRIPT_LABEL}:Import Self-Report (selfreport2csv)" \
      ${SIBIS}/scripts/import/laptops/selfreport2csv /fs/storage/laptops/imported --no-output ${qa_args}
else
   if [ ${hour} -eq 0 ]; then
      echo "${SCRIPT_LABEL}: Warning: Import from laptops  disabled !"
   fi
fi

#
# Previouly front-nighlty
#

# REDCap updates
update_args=""
if [ ${hour} -eq 0 ]; then
    update_args+="--update-all"
fi
catch_output_email "${SCRIPT_LABEL}:REDCap: Update Scores (redcap_update_summary_scores)" $SIBIS_PYTHON_PATH/sibispy/cmds/redcap_update_summary_scores.py ${update_args} ${qa_args}

