#!/bin/bash

##
##  Copyright 2015 SRI International
##  See COPYING file distributed along with the package for the copyright and license terms.
##

# Set the SIBIS environment variable to the data integration repo
export SIBIS=${HOME}/ncanda-data-integration

[ -r $HOME/.bashrc ] && . $HOME/.bashrc

# Import some useful functions
. $(dirname $0)/crontools.sh

######################################
# XNAT / Imaging Related
######################################

# Check MR session names etc. in XNAT
catch_output_email ncanda-admin@sri.com "NCANDA XNAT: Check Object Names Messgae (check_object_names)" ${SIBIS}/scripts/xnat/check_object_names --send-mail --zip-root /fs/storage/share/burn2dvd

# Check for new or updated sessions and
catch_output_email ncanda-admin@sri.com "NCANDA XNAT: Check New Sessions Message (check_new_sessions)" ${SIBIS}/scripts/xnat/check_new_sessions --send-mail-to dolf@synapse.sri.com,kilian.pohl@sri.com,nolan.nichols@gmail.com,yzhang83@stanford.edu,aleberre@stanford.edu,sanghyun.park@sri.com

# Check whether any MR sessions are missing corresponding phantom scans
catch_output_email ncanda-admin@sri.com "NCANDA XNAT: Phantom Scan Messages (check_phantom_scans)" ${SIBIS}/scripts/xnat/check_phantom_scans --check-all

# Run fMRI QA on subjects ## Currently disabled because it isn't looked at but takes a long time to run
##catch_output_email ncanda-admin@sri.com "NCANDA XNAT: Subject fMRI QA Messages" ${SIBIS}/scripts/xnat/fmri_qa_subjects

######################################
# REDCap / NP / Clinical Data Related
######################################

# Import data from UPenn into REDCap
catch_output_email ncanda-admin@sri.com "NCANDA REDCap: WebCNP Import Messages (cnp2redcap)" ${SIBIS}/scripts/import/webcnp/cnp2redcap --last-3-months

# Check whether subject birth dates and gender match checksum digit, plus whether all subjects on study arms appear in main arm also
catch_output_email ncanda-admin@sri.com "NCANDA REDCap: Subject ID Checks (check_subject_ids)" ${SIBIS}/scripts/redcap/check_subject_ids

# Check (and update, if necessary) drinking exception status
catch_output_email ncanda-admin@sri.com "NCANDA REDCap: Undeclared Drinking Exceptions (check_exceptions)" ${SIBIS}/scripts/redcap/check_exceptions --update-fn
