#!/bin/bash

##
##  Copyright 2015 SRI International
##  License: https://ncanda.sri.com/software-license.txt
##
##  $Revision$
##  $LastChangedBy$
##  $LastChangedDate$
##

# Set the SIBIS environment variable to the data integration repo
export SIBIS=${HOME}/ncanda-data-integration

[ -r $HOME/.bashrc ] && . $HOME/.bashrc

# Import some useful functions
. $(dirname $0)/crontools.sh

# Run QA on fBIRN and ADNI phantom scans
catch_output_email ncanda-admin@sri.com "NCANDA XNAT: Phantom QA Messages (phantom_qa)" ${SIBIS}/scripts/xnat/phantom_qa

# Import data from the sites' data capture laptops into REDCap and reconcile imported with longitudinal data
catch_output_email ncanda-admin@sri.com "NCANDA: Laptop Data Import Stage 1 (harvester)" ${SIBIS}/scripts/import/laptops/harvester ${HOME}/laptops/ncanda ${HOME}/laptops/imported

# At midnight PST, run full update; otherwise, add only previously-missing data
update_args=""
hour=$(date +%H)
if [ ${hour} -ne 0 ]; then
    update_args+=" --missing-only"
fi

catch_output_email ncanda-admin@sri.com "NCANDA: Laptop Data Import Stage 2 (update_visit_date)" ${SIBIS}/scripts/import/laptops/update_visit_data --max-days-after-visit 120 ${update_args}

# REDCap updates
update_args=""
hour=$(date +%H)
if [ ${hour} -eq 0 ]; then
    update_args+="--update-all"
fi
catch_output_email ncanda-admin@sri.com "NCANDA REDCap: Update Scores (update_summary_scores)" ${SIBIS}/scripts/redcap/update_summary_scores ${update_args}

catch_output_email ncanda-admin@sri.com "NCANDA REDCap: Update Form Status (update_bulk_forms)" ${SIBIS}/scripts/redcap/update_bulk_forms
