#!/bin/bash

##
##  Copyright 2015 SRI International
##  License: https://ncanda.sri.com/software-license.txt
##
##  $Revision: 2114 $
##  $LastChangedBy: dj0330 $
##  $LastChangedDate: 2015-08-07 09:42:11 -0700 (Fri, 07 Aug 2015) $
##

[ -r $HOME/.bashrc ] && . $HOME/.bashrc

# Import some useful functions
. $(dirname $0)/crontools.sh

# Run QA on fBIRN and ADNI phantom scans
catch_output_email nolan.nichols@gmail.com,kilian.pohl@sri.com "NCANDA XNAT: Phantom QA Messages (phantom_qa)" ${HOME}/scripts/xnat/phantom_qa

# Import data from the sites' data capture laptops into REDCap and reconcile imported with longitudinal data
catch_output_email weiwei.chu@sri.com,nolan.nichols@gmail.com "NCANDA: Laptop Data Import Stage 1 (harvester)" ${HOME}/scripts/import/laptops/harvester ${HOME}/laptops/ncanda ${HOME}/laptops/imported

# At midnight PST, run full update; otherwise, add only previously-missing data
update_args=""
hour=$(date +%H)
if [ ${hour} -ne 0 ]; then
    update_args+=" --missing-only"
fi

catch_output_email weiwei.chu@sri.com,nolan.nichols@gmail.com "NCANDA: Laptop Data Import Stage 2 (update_visit_date)" ${HOME}/scripts/import/laptops/update_visit_data --max-days-after-visit 120 ${update_args}

# REDCap updates
update_args=""
hour=$(date +%H)
if [ ${hour} -eq 0 ]; then
    update_args+="--update-all"
fi
catch_output_email weiwei.chu@sri.com,nolan.nichols@gmail.com "NCANDA REDCap: Update Scores (update_summary_scores)" ${HOME}/scripts/redcap/update_summary_scores ${update_args}

catch_output_email weiwei.chu@sri.com,nolan.nichols@gmail.com "NCANDA REDCap: Update Form Status (update_bulk_forms)" ${HOME}/scripts/redcap/update_bulk_forms
