#!/bin/bash

##
##  Copyright 2015 SRI International
##  License: https://ncanda.sri.com/software-license.txt
##
##  $Revision: 2114 $
##  $LastChangedBy: dj0330 $
##  $LastChangedDate: 2015-08-07 09:42:11 -0700 (Fri, 07 Aug 2015) $
##

[ -r $HOME/.bashrc ] && . $HOME/.bashrc

# Import some useful functions
. $(dirname $0)/crontools.sh

######################################
# XNAT / Imaging Related
######################################

# Check MR session names etc. in XNAT
catch_output_email nolan.nichols@gmail.com,kilian.pohl@sri.com "NCANDA XNAT: Check Object Names Messgae (check_object_names)" ${HOME}/scripts/xnat/check_object_names --send-mail --zip-root /fs/storage/share/burn2dvd

# Check for new or updated sessions and
catch_output_email nolan.nichols@gmail.com,kilian.pohl@sri.com "NCANDA XNAT: Check New Sessions Message (check_new_sessions)" ${HOME}/scripts/xnat/check_new_sessions --send-mail-to dolf@synapse.sri.com,kilian.pohl@sri.com,nolan.nichols@gmail.com,yzhang83@stanford.edu

# Check whether any MR sessions are missing corresponding phantom scans
catch_output_email nolan.nichols@gmail.com,kilian.pohl@sri.com "NCANDA XNAT: Phantom Scan Messages (check_phantom_scans)" ${HOME}/scripts/xnat/check_phantom_scans --check-all

# Run fMRI QA on subjects ## Currently disabled because it isn't looked at but takes a long time to run
##catch_output_email daniel.cuneo@sri.com "NCANDA XNAT: Subject fMRI QA Messages" ${HOME}/scripts/xnat/fmri_qa_subjects

######################################
# REDCap / NP / Clinical Data Related
######################################

# Import data from UPenn into REDCap
catch_output_email weiwei.chu@sri.com,nolan.nichols@gmail.com "NCANDA REDCap: WebCNP Import Messages (cnp2redcap)" ${HOME}/scripts/import/webcnp/cnp2redcap --last-3-months

# Check whether subject birth dates and gender match checksum digit, plus whether all subjects on study arms appear in main arm also
catch_output_email weiwei.chu@sri.com,nolan.nichols@gmail.com "NCANDA REDCap: Subject ID Checks (check_subject_ids)" ${HOME}/scripts/redcap/check_subject_ids

# Check (and update, if necessary) drinking exception status
catch_output_email weiwei.chu@sri.com,nolan.nichols@gmail.com "NCANDA REDCap: Undeclared Drinking Exceptions (check_exceptions)" ${HOME}/scripts/redcap/check_exceptions --update-fn
