#!/bin/bash

##
##  Copyright 2016 SRI International
##  See COPYING file distributed along with the package for the copyright and license terms.
##
##  $HeadURL: https://www.nitrc.org/svn/ncanda-datacore/trunk/utils/concat_csv $
##  $Revision: 2636 $
##  $LastChangedDate: 2016-12-07 10:49:04 -0800 (Wed, 07 Dec 2016) $
##  $LastChangedBy: dj0330 $
##

if [ "$2" == "" ]; then
  echo "Current Call: $0 $@"
  echo "Please define output summary file and list of csv files to generate summary over"
  echo "e.g. concat_csv output.csv */*/*/measures/demographics.csv"
  exit 1
fi

OUTPUT_FILE=$1
shift
FIRST_CSV=$1
shift
REST_CSV=$@
if [ -e ${OUTPUT_FILE} ]; then
  rm -f ${OUTPUT_FILE}
fi 

if [ ! -e ${FIRST_CSV} ]; then 
    echo "ERROR: ${FIRST_CSV} does not exist !"
    exit 1
fi 

cp -f ${FIRST_CSV} ${OUTPUT_FILE}

for CSV in ${REST_CSV}; do
  tail -n+2 $CSV >> ${OUTPUT_FILE}
done
