#!/usr/bin/env python

##
##  Copyright 2012-2014 SRI International
##
##  http://nitrc.org/projects/ncanda-datacore/
##
##  This file is part of the N-CANDA Data Component Software Suite, developed
##  and distributed by the Data Integration Component of the National
##  Consortium on Alcohol and NeuroDevelopment in Adolescence, supported by
##  the U.S. National Institute on Alcohol Abuse and Alcoholism (NIAAA) under
##  Grant No. 1U01 AA021697
##
##  The N-CANDA Data Component Software Suite is free software: you can
##  redistribute it and/or modify it under the terms of the GNU General Public
##  License as published by the Free Software Foundation, either version 3 of
##  the License, or (at your option) any later version.
##
##  The N-CANDA Data Component Software Suite is distributed in the hope that it
##  will be useful, but WITHOUT ANY WARRANTY; without even the implied
##  warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##  GNU General Public License for more details.
##
##  You should have received a copy of the GNU General Public License along
##  with the N-CANDA Data Component Software Suite.  If not, see
##  <http://www.gnu.org/licenses/>.
##
##  $Revision: 674 $
##
##  $LastChangedDate: 2013-11-12 13:47:34 -0800 (Tue, 12 Nov 2013) $
##
##  $LastChangedBy: torstenrohlfing $
##

import argparse
import sys
import os
import re
import subprocess
import tempfile
import shutil

import pandas

import redcap
import pyxnat

# Setup command line parser
parser = argparse.ArgumentParser( description="For all subjects and visits with MR reports in the REDCap database, find MR Stroop files and upload to REDCap", formatter_class=argparse.ArgumentDefaultsHelpFormatter )
parser.add_argument( "-v", "--verbose", help="Verbose operation", action="store_true")
parser.add_argument( "--max-days-after-visit", help="Maximum number of days the scan session can be after the entered 'visit date' in REDCap to be assigned to a given event.", action="store", default=30, type=int)
parser.add_argument( "-f", "--force-update", help="Update all records in REDCap, overwriting existing data", action="store_true")
parser.add_argument( "-e", "--with-excluded", help="Include records marked 'excluded' in REDCap", action="store_true")
parser.add_argument( "-n", "--no-upload", help="Only check correspondences; do not upload results to REDCap", action="store_true")
args = parser.parse_args()

#
# Check for Stroop data (ePrime log file) in given XNAT session
#
import_bindir = os.path.join( os.path.dirname( os.path.dirname( os.path.abspath(__file__) ) ), 'import', 'laptops' )
bindir = os.path.dirname( os.path.abspath(__file__) )

def check_for_stroop( xnat, xnat_eid, redcap_token, redcap_key, verbose=False, no_upload=False ):
    experiment = xnat.select.experiment( xnat_eid )

    # Get list of resource files that match the Stroop file name pattern
    experiment_files = []
    for resource in  experiment.resources().get():
        resource_files = xnat._get_json( '/data/experiments/%s/resources/%s/files?format=json' % ( xnat_eid, resource ) );
        experiment_files += [ (resource, re.sub( '.*\/files\/', '', file['URI']) ) for file in resource_files if re.match( '^NCANDAStroopMtS_3cycles_7m53stask_.*.txt$', file['Name'] ) ]
        
    # No matching files - nothing to do
    if len( experiment_files ) == 0:
        return

    # Get first file from list, warn if more files
    (stroop_resource, stroop_file) = experiment_files[0]
    if len( experiment_files ) > 1:
        print "WARNING: experiment",xnat_eid,"has more than one Stroop .txt file - using file",stroop_file

    if verbose:
        print "Importing Stroop data from file %s:%s" % ( xnat_eid, stroop_file )

    # Download Stroop file from XNAT into temporary directory
    tempdir = tempfile.mkdtemp()
    stroop_file_path = experiment.resource( stroop_resource ).file( stroop_file ).get_copy( os.path.join( tempdir, stroop_file ) )

    # Convert downloaded Stroop file to CSV scores file
    added_files = subprocess.check_output( [ os.path.join( import_bindir, "stroop2csv" ), '--mr-session', '--record', redcap_key[0], '--event', redcap_key[1], stroop_file_path, tempdir ] )
    if len( added_files ):
        if not no_upload:
            # Upload CSV file(s) (should only be one anyway)
            for file in added_files.split( '\n' ):
                if re.match( '.*\.csv$', file ):
                    if verbose:
                        print "Uploading ePrime Stroop scores",file
                    subprocess.call( [ os.path.join( bindir, 'csv2redcap' ), file ] )            
            # Upload original ePrime file for future reference
            if verbose:
                print "Uploading ePrime Stroop file",stroop_file_path
            subprocess.check_output( [ os.path.join( import_bindir, "eprime2redcap" ), "--api-key", redcap_token, '--record', redcap_key[0], '--event', redcap_key[1], stroop_file_path, 'mri_stroop_log_file' ] )
    else:
        print "ERROR: could not convert Stroop file %s:%s" % ( xnat_eid, stroop_file )

    shutil.rmtree( tempdir )

# Open connection with REDCap server
redcap_token_path = os.path.join( os.path.expanduser("~"), '.server_config/redcap-dataentry-token' )
redcap_token_file = open( redcap_token_path, 'r' )
redcap_token = redcap_token_file.read().strip()

redcap_project = redcap.Project( 'https://ncanda.sri.com/redcap/api/', redcap_token, verify_ssl=False)
form_event_mapping = redcap_project.export_fem( format='df' )

# Open connection with XNAT server
xnat = pyxnat.Interface( config = os.path.join( os.path.expanduser("~"), '.server_config/ncanda.cfg' ) )

#
# Main program loop
#
visit_log_redcap = redcap_project.export_records(fields=['dob', 'exclude', 'visit_date', 'mri_xnat_eids', 'mr_session_report_complete', 'mri_stroop_complete'], event_name='unique', format='df' )

# Select only events that have the "MRI Session Report" form
mri_events_list = form_event_mapping[form_event_mapping['form_name'] == 'mr_session_report' ]['unique_event_name'].tolist()
mr_sessions_redcap = visit_log_redcap[ visit_log_redcap.index.map( lambda x: x[1] in mri_events_list ) ][['visit_date', 'mri_xnat_eids', 'mr_session_report_complete', 'mri_stroop_complete']]
mr_sessions_redcap = mr_sessions_redcap[ mr_sessions_redcap['mr_session_report_complete'] > 0 ]

subject_data = visit_log_redcap.xs( 'baseline_visit_arm_1', level=1 )

# Filter out all records marked as "Complete", unless user instructed otherwise
if not args.force_update:
    mr_sessions_redcap = mr_sessions_redcap[ mr_sessions_redcap['mri_stroop_complete'] < 2 ]

if args.verbose:
    print "Checking %d REDCap records." % len( mr_sessions_redcap )

# Iterate over all remaining rows
for [key,row] in mr_sessions_redcap.iterrows():
    if not subject_data['exclude'][key[0]] or args.with_excluded:
        visit_date = str(visit_log_redcap['visit_date'][key])
        if visit_date == 'nan':
            print "Missing '%s' date for subject %s" % ( key[1], key[0] )
        else:
            try:
                for xnat_eid in row['mri_xnat_eids'].split( ' ' ):
                    check_for_stroop( xnat, xnat_eid, redcap_token, key, verbose=args.verbose, no_upload=args.no_upload )
            except AttributeError, e:
                print "Error for xnat_eid: {0}...{1}".format(xnat_eid, e)
