#!/usr/bin/env python

##
##  See COPYING file distributed along with the ncanda-data-integration package
##  for the copyright and license terms
##

import os
import re
import sys
import json
import time

import pyxnat

import fmri_qa_functions as qa
import t1_qa_functions as t1qa

# Define command line options for this script
from optparse import OptionParser
parser = OptionParser()
parser.add_option("-v", "--verbose", action="store_true", dest="verbose", default=False, help="Verbose operation.")
parser.add_option("-f", "--force-updates", action="store_true", dest="force_updates", default=False, help="Force updates of QA analyses for all phantom scan experiments.")
parser.add_option("-a", "--check-all", action="store_true", dest="check_all", default=False, help="Check all phantom sessions, regardless of date.")
parser.add_option("--exclude-adni", action="store_true", dest="exclude_adni", default=False, help="Exclude all (structural) ADNI phantom scans.")
parser.add_option("--exclude-fbirn", action="store_true", dest="exclude_fbirn", default=False, help="Exclude all (functional) fBIRN phantom scans.")
parser.add_option("--subj-id", action="store", dest="subj_id", default=None, help="Limit processing by subject_id")
(options, args) = parser.parse_args()

# Create interface using stored configuration
interface = pyxnat.Interface( config = os.path.join( os.path.expanduser("~"), '.server_config/ncanda.cfg' ) )
interface._memtimeout = 0

# Date format for XNAT dates
xnat_date_format = '%Y-%m-%d %H:%M:%S'
now_str = time.strftime( xnat_date_format )

# Date (and time) when we last checked things
date_last_checked = time.localtime(0)
config_uri = '/data/config/pyxnat/fmri_qa_phantom'
try:
    # Retrieve script config from XNAT server
    content = interface._exec( '%s?format=json' % config_uri )
    # Extract date this script was last run
    creation_date = json.loads( content )['ResultSet']['Result'][0]['create_date']
    date_last_checked = time.strptime( creation_date[0:19], xnat_date_format )
    if options.verbose:
        print 'Script was last run %s' % creation_date
except:
    # If we cannot get last script run date from server, leave at epoch (Jan 1, 1970)    
    if options.verbose:
        print 'Unable to retrieve date of last script run from server.'

# For comparison - convert time of last check to string in XNAT date format
str_date_last_checked = time.strftime( xnat_date_format, date_last_checked )


def process_fbirn(phantom_subjects_IDs):

    for [phantom, project, label] in phantom_subject_IDs:
        # For each phantom subject (one per project), get the IDs and last_modified dates of all its imaging sessions
        phantom_sessions = interface.select('xnat:mrSessionData',
                                            ['xnat:mrSessionData/SESSION_ID', 'xnat:mrSessionData/LABEL',
                                             'xnat:mrSessionData/LAST_MODIFIED']) \
            .where([('xnat:mrSessionData/SUBJECT_ID', 'LIKE', phantom)]).items()
        print 'phantom_sessions: {}'.format(phantom_sessions)
        # Iterate over all imaging sessions
        for [session, label, last_modified] in phantom_sessions:
            if (last_modified > str_date_last_checked) or options.force_updates \
                    or options.check_all or options.subj_id:
                if options.verbose:
                    print 'Running fBIRN phantom QA for session {0} in project {1}'.format(session, project)
                qa.process_phantom_session(interface, project, phantom, session,
                                           label, force_updates=options.force_updates)

def process_adni(phantom_subjects_IDs):

    for [phantom, project, label] in phantom_subject_IDs:
        print 'phantom: {}'.format(phantom)
        # For each phantom subject (one per project), get the IDs and last_modified dates of all its imaging sessions
        phantom_sessions = interface.select('xnat:mrSessionData',
                                            ['xnat:mrSessionData/SESSION_ID', 'xnat:mrSessionData/LABEL',
                                             'xnat:mrSessionData/LAST_MODIFIED']) \
            .where([('xnat:mrSessionData/SUBJECT_ID', 'LIKE', phantom)]).items()
        print 'phantom_sessions: {}'.format(phantom_sessions)
        # Iterate over all imaging sessions
        for [session, label, last_modified] in phantom_sessions:
            if (last_modified > str_date_last_checked) or options.force_updates \
                    or options.check_all or options.subj_id:
                if options.verbose:
                    print 'Running ADNI phantom QA for session {0} in project {1}'.format(session, project)
                t1qa.process_phantom_session(interface, project, phantom, session, label,
                                             force_updates=options.force_updates)

if options.subj_id:
    # Adjust the constraints for one subject id
    constraints = [('xnat:subjectData/SUBJECT_ID', '=', options.subj_id)]
    # Search XNAT database for all Subjects that have the fBIRN with constraints from parameter
    phantom_subject_IDs = interface.select('xnat:subjectData',
                                           ['xnat:subjectData/SUBJECT_ID', 'xnat:subjectData/PROJECT',
                                           'xnat:subjectData/SUBJECT_LABEL']) \
                                           .where(constraints).items()
    print 'phantom_subjects_IDs: {}'.format(phantom_subject_IDs)
    for subject_id, project, label in phantom_subject_IDs:
        if re.match('^[A-Z]-00000-P-0', label):
            process_fbirn(phantom_subject_IDs)
        elif re.match('^[A-Z]-99999-P-9',label):
            process_adni(phantom_subject_IDs)
        else:
            print "subject_label did not match re for phantom label '^[A-Z]-00000-P-0' or '^[A-Z]-99999-P-9'"
            sys.exit(1)


if options.exclude_adni:
    # General constraints to get all fBIRN phantoms
    constraints = [('xnat:subjectData/SUBJECT_LABEL', 'LIKE','%-00000-P-0')]
    # Search XNAT database for all Subjects that have the fBIRN with constraints from parameter
    phantom_subject_IDs = interface.select('xnat:subjectData',
                                           ['xnat:subjectData/SUBJECT_ID', 'xnat:subjectData/PROJECT',
                                            'xnat:subjectData/SUBJECT_LABEL']) \
                                           .where(constraints).items()
    print 'pahntom_subkect_ID: {}'.format(phantom_subject_IDs)
    process_fbirn(phantom_subject_IDs)

if options.exclude_fbirn:
    # General constraints to get all adni phantoms
    constraints = [('xnat:subjectData/SUBJECT_LABEL', 'LIKE', '%-99999-P-9')]
    # Search XNAT database for all Subjects that have the fBIRN with constraints from parameter
    phantom_subject_IDs = interface.select('xnat:subjectData',
                                           ['xnat:subjectData/SUBJECT_ID', 'xnat:subjectData/PROJECT',
                                            'xnat:subjectData/SUBJECT_LABEL']) \
        .where(constraints).items()
    print 'pahntom_subject_ID: {}'.format(phantom_subject_IDs)
    process_adni(phantom_subject_IDs)

# Finally, update config stored on the server to have current date/time as the time that this script was last run
# (but don't update config if we excluded either ADNI of fBIRN phantom scans this time around)
if not options.exclude_fbirn and not options.exclude_adni:
    content = interface._exec( uri='%s?inbody=true' % config_uri, method='PUT', body=now_str, headers={'content-type':'text/plain'} )
