#!/bin/bash
# this script is intended to replace backup_redcap_dbdir
backup_tgt=/data/mariadb-redcap-archive
date_file=$backup_tgt/mysql/ARCHIVE_DATE.txt

REDCAP_MARIA_CONTAINER_NAME=mariadb_redcap
REDCAP_MYSQL_DATABASE=redcap
REDCAP_MYSQL_ROOT_PASSWORD=root
MYSQL_IGNORE="--ignore-table-data=redcap.redcap_log_view --ignore-table-data=redcap.redcap_log_event --ignore-table-data=redcap.redcap_log_view_old"
MYSQL_DUMP="mysqldump -u root -p${REDCAP_MYSQL_ROOT_PASSWORD} ${MYSQL_IGNORE} --quick --compress --verbose --debug-info --single-transaction --databases ${REDCAP_MYSQL_DATABASE}"

function current_timestamp() {
    # 20240321T034445z
    local cur_time
    cur_time=$(date --utc "+%Y%m%dT%H%M%Sz")
    printf "%s" "$cur_time"
}

START_TIME=$(current_timestamp)

set -e
# set -x
DST_FILE="${backup_tgt}/redcap_mariadb_backup-$(current_timestamp).sql.gz"
docker exec -t ${REDCAP_MARIA_CONTAINER_NAME} ${MYSQL_DUMP} | gzip  > "${DST_FILE}"
# set +x

COMPLETE_TIME=$(current_timestamp)

#add date file
printf "\n\n### Adding Date File\n"
printf 'Start: %s End: %s\n' "$START_TIME" "$COMPLETE_TIME" >> "$date_file"

# docker container should have started
printf "\n\n### Completed backup.\n"


