#!/bin/bash
# this script is intended to replace backup_redcap_dbdir
backup_tgt=/data/mariadb-redcap-archive
date_file=$backup_tgt/mysql/ARCHIVE_DATE.txt

REDCAP_MARIA_CONTAINER_NAME=mariadb_redcap
REDCAP_MYSQL_DATABASE=redcap
REDCAP_MYSQL_BACKUP_IGNORE="--ignore-table-data=redcap.redcap_log_view --ignore-table-data=redcap.redcap_log_event --ignore-table-data=redcap.redcap_log_view_old"
REDCAP_MYSQL_ROOT_PASSWORD=root
DST_GZIP_FILE=${backup_tgt}/redcap_mariadb_backup-`date -Iseconds | sed s/:/-/g`.sql.gz

function current_timestamp() {
    # 20240321T034445+0000
    local cur_time
    cur_time=$(date --utc "+%Y%m%dT%H%M%S%z")
    printf "%s" "$cur_time"
}

START_TIME=$(current_timestamp)

set -e
set -x
docker exec -t ${REDCAP_MARIA_CONTAINER_NAME} mysqldump -u root -p${REDCAP_MYSQL_ROOT_PASSWORD} ${REDCAP_MYSQL_BACKUP_IGNORE} --quick --compress --verbose --debug-info --single-transaction --databases ${REDCAP_MYSQL_DATABASE} | gzip > "${DST_GZIP_FILE}"
set +x

COMPLETE_TIME=$(current_timestamp)

#add date file
printf "\n\n### Adding Date File\n"
printf 'Start: %s End: %s\n' "$START_TIME" "$COMPLETE_TIME" >> "$date_file"

# docker container should have started
printf "\n\n### Completed backup.\n"


