#!/bin/sh

##
##  Copyright 2012-2014 SRI International
##
##  http://nitrc.org/projects/ncanda-datacore/
##
##  This file is part of the N-CANDA Data Component Software Suite, developed
##  and distributed by the Data Integration Component of the National
##  Consortium on Alcohol and NeuroDevelopment in Adolescence, supported by
##  the U.S. National Institute on Alcohol Abuse and Alcoholism (NIAAA) under
##  Grant No. 1U01 AA021697
##
##  The N-CANDA Data Component Software Suite is free software: you can
##  redistribute it and/or modify it under the terms of the GNU General Public
##  License as published by the Free Software Foundation, either version 3 of
##  the License, or (at your option) any later version.
##
##  The N-CANDA Data Component Software Suite is distributed in the hope that it
##  will be useful, but WITHOUT ANY WARRANTY; without even the implied
##  warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##  GNU General Public License for more details.
##
##  You should have received a copy of the GNU General Public License along
##  with the N-CANDA Data Component Software Suite.  If not, see
##  <http://www.gnu.org/licenses/>.
##
##  $Revision$
##
##  $LastChangedDate$
##
##  $LastChangedBy$
##

# Upload file to S3
upload_to_s3()
{
    local fname=`basename $1`

    # Get last digit of day-of-year to rotate file names around and keep 10 copies
    local day=`date +%j | sed 's/^..//g'`

    if ! s3cmd --server-side-encryption put ${1} s3://ncanda/db/${day}/${fname}; then
	echo "FAILURE: unable to upload archive ${1} to S3"
    else
	rm ${1}
    fi
}

if cd /mnt/svn; then
    gtar --xz -cf - ncanda* | aespipe -P ${HOME}/aes/keys -e aes256 > /var/tmp/subversion.tar.gz.aes
    upload_to_s3 /var/tmp/subversion.tar.gz.aes
else
    echo "ERROR: /mnt/svn is not available - Subversion repositories not archived"
fi
