#!/bin/bash -l

##
##  See COPYING file distributed along with the ncanda-data-integration package
##  for the copyright and license terms
##

MAILTO="ncanda-admin@sri.com,jim.klo@sri.com"
bindir=`dirname $0`
$bindir/transmit_xnat || echo "transmit_xnat failed"
$bindir/transmit_dbs || echo "transmit_dbs failed"
$bindir/transmit_svn || echo "transmit_svn failed"
