#!/bin/bash -l

##
##  See COPYING file distributed along with the ncanda-data-integration package
##  for the copyright and license terms
##

bindir=`dirname $0`

$bindir/transmit_xnat
$bindir/transmit_dbs
$bindir/transmit_svn
