#!/bin/bash -l 

##
##  See COPYING file distributed along with the ncanda-data-integration package
##  for the copyright and license terms
##
script_dir=`dirname $0`
backup_tmp=/fs/snapshots
retain_local_redcap=0

# Load common transmit utils
source $script_dir/transmit_utils

# MariaDB first - this can be run as root
#${script_dir}/backup_mariadb

# PostgreSQL backup for XNAT
${script_dir}/backup_pgsql

# REDCap file uploads backup
${script_dir}/backup_redcap_files
