#!/bin/bash -l

##
##  See COPYING file distributed along with the ncanda-data-integration package
##  for the copyright and license terms
##

# Upload file to S3
upload_to_s3()
{
    local fname=`basename $1`

    # Get last digit of day-of-year to rotate file names around and keep 10 copies
    local day=`date +%j | sed 's/^..//g'`

    if ! s3cmd --server-side-encryption put ${1} s3://ncanda/db/${day}/${fname}; then
	echo "FAILURE: unable to upload archive ${1} to S3"
    else
	rm ${1}
    fi
}

DIR=/fs/storage/laptops/
if cd $DIR; then
    gtar --xz -cf - ncanda* | aespipe -P ${HOME}/aes/keys -e aes256 > /var/tmp/subversion.tar.gz.aes
    upload_to_s3 /var/tmp/subversion.tar.gz.aes
else
    echo "ERROR: $DIR is not available - Subversion repositories not archived"
fi
